/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [CustomerKey]
      --,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      ,[FirstName] AS [First Name]
      --,[MiddleName]
      ,[LastName] AS [Last Name]
	  ,[FirstName] + ' ' + [LastName] AS [Full Name]
      --,[NameStyle]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Suffix]
      ,CASE [Gender] WHEN 'M' THEN 'Male' WHEN 'F' THEN 'Female' END AS [Gender]
      --,[EmailAddress]
      --,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,[DateFirstPurchase] AS [Purchase Date]
      --,[CommuteDistance]
	  ,[City] AS [Customer City]
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer]
  LEFT JOIN DimGeography on DimGeography.GeographyKey = DimCustomer.GeographyKey
  ORDER BY CustomerKey ASC